// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package demo

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDemo returns the embedded CollectionSpec for demo.
func loadDemo() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DemoBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load demo: %w", err)
	}

	return spec, err
}

// loadDemoObjects loads demo and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*demoObjects
//	*demoPrograms
//	*demoMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDemoObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDemo()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// demoSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type demoSpecs struct {
	demoProgramSpecs
	demoMapSpecs
	demoVariableSpecs
}

// demoProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type demoProgramSpecs struct {
	AfterCiliumHost  *ebpf.ProgramSpec `ebpf:"after_cilium_host"`
	AfterCiliumLxc   *ebpf.ProgramSpec `ebpf:"after_cilium_lxc"`
	BeforeCiliumHost *ebpf.ProgramSpec `ebpf:"before_cilium_host"`
	BeforeCiliumLxc  *ebpf.ProgramSpec `ebpf:"before_cilium_lxc"`
}

// demoMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type demoMapSpecs struct {
	CiliumReturn *ebpf.MapSpec `ebpf:"cilium_return"`
}

// demoVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type demoVariableSpecs struct {
	Direction  *ebpf.VariableSpec `ebpf:"direction"`
	EndpointId *ebpf.VariableSpec `ebpf:"endpoint_id"`
}

// demoObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDemoObjects or ebpf.CollectionSpec.LoadAndAssign.
type demoObjects struct {
	demoPrograms
	demoMaps
	demoVariables
}

func (o *demoObjects) Close() error {
	return _DemoClose(
		&o.demoPrograms,
		&o.demoMaps,
	)
}

// demoMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDemoObjects or ebpf.CollectionSpec.LoadAndAssign.
type demoMaps struct {
	CiliumReturn *ebpf.Map `ebpf:"cilium_return"`
}

func (m *demoMaps) Close() error {
	return _DemoClose(
		m.CiliumReturn,
	)
}

// demoVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDemoObjects or ebpf.CollectionSpec.LoadAndAssign.
type demoVariables struct {
	Direction  *ebpf.Variable `ebpf:"direction"`
	EndpointId *ebpf.Variable `ebpf:"endpoint_id"`
}

// demoPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDemoObjects or ebpf.CollectionSpec.LoadAndAssign.
type demoPrograms struct {
	AfterCiliumHost  *ebpf.Program `ebpf:"after_cilium_host"`
	AfterCiliumLxc   *ebpf.Program `ebpf:"after_cilium_lxc"`
	BeforeCiliumHost *ebpf.Program `ebpf:"before_cilium_host"`
	BeforeCiliumLxc  *ebpf.Program `ebpf:"before_cilium_lxc"`
}

func (p *demoPrograms) Close() error {
	return _DemoClose(
		p.AfterCiliumHost,
		p.AfterCiliumLxc,
		p.BeforeCiliumHost,
		p.BeforeCiliumLxc,
	)
}

func _DemoClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed demo_bpfeb.o
var _DemoBytes []byte
