// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: datapathplugins/datapathplugins.proto

package datapathplugins

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HookType int32

const (
	HookType_PRE  HookType = 0
	HookType_POST HookType = 1
)

// Enum value maps for HookType.
var (
	HookType_name = map[int32]string{
		0: "PRE",
		1: "POST",
	}
	HookType_value = map[string]int32{
		"PRE":  0,
		"POST": 1,
	}
)

func (x HookType) Enum() *HookType {
	p := new(HookType)
	*p = x
	return p
}

func (x HookType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HookType) Descriptor() protoreflect.EnumDescriptor {
	return file_datapathplugins_datapathplugins_proto_enumTypes[0].Descriptor()
}

func (HookType) Type() protoreflect.EnumType {
	return &file_datapathplugins_datapathplugins_proto_enumTypes[0]
}

func (x HookType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HookType.Descriptor instead.
func (HookType) EnumDescriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{0}
}

type PrepareHooksResponse_HookSpec_OrderingConstraint_Order int32

const (
	PrepareHooksResponse_HookSpec_OrderingConstraint_BEFORE PrepareHooksResponse_HookSpec_OrderingConstraint_Order = 0
	PrepareHooksResponse_HookSpec_OrderingConstraint_AFTER  PrepareHooksResponse_HookSpec_OrderingConstraint_Order = 1
)

// Enum value maps for PrepareHooksResponse_HookSpec_OrderingConstraint_Order.
var (
	PrepareHooksResponse_HookSpec_OrderingConstraint_Order_name = map[int32]string{
		0: "BEFORE",
		1: "AFTER",
	}
	PrepareHooksResponse_HookSpec_OrderingConstraint_Order_value = map[string]int32{
		"BEFORE": 0,
		"AFTER":  1,
	}
)

func (x PrepareHooksResponse_HookSpec_OrderingConstraint_Order) Enum() *PrepareHooksResponse_HookSpec_OrderingConstraint_Order {
	p := new(PrepareHooksResponse_HookSpec_OrderingConstraint_Order)
	*p = x
	return p
}

func (x PrepareHooksResponse_HookSpec_OrderingConstraint_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrepareHooksResponse_HookSpec_OrderingConstraint_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_datapathplugins_datapathplugins_proto_enumTypes[1].Descriptor()
}

func (PrepareHooksResponse_HookSpec_OrderingConstraint_Order) Type() protoreflect.EnumType {
	return &file_datapathplugins_datapathplugins_proto_enumTypes[1]
}

func (x PrepareHooksResponse_HookSpec_OrderingConstraint_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrepareHooksResponse_HookSpec_OrderingConstraint_Order.Descriptor instead.
func (PrepareHooksResponse_HookSpec_OrderingConstraint_Order) EnumDescriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{3, 0, 0, 0}
}

// LocalNodeConfig is Cilium's current config for this node. It may be used
// by plugins to decide which hooks to load, how to configure them, etc.
type LocalNodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalNodeConfig) Reset() {
	*x = LocalNodeConfig{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalNodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalNodeConfig) ProtoMessage() {}

func (x *LocalNodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalNodeConfig.ProtoReflect.Descriptor instead.
func (*LocalNodeConfig) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{0}
}

// AttachmentContext contains the context about the attachment point in
// question. It may carry endpoint-specific information used to determine which
// hooks to load or how to configure them.
type AttachmentContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// context contains information about the attachment context. Add more
	// fields for future attachment contexts like XDP, CgroupSock, etc.
	//
	// Types that are valid to be assigned to Context:
	//
	//	*AttachmentContext_Tc
	Context       isAttachmentContext_Context `protobuf_oneof:"context"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentContext) Reset() {
	*x = AttachmentContext{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentContext) ProtoMessage() {}

func (x *AttachmentContext) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentContext.ProtoReflect.Descriptor instead.
func (*AttachmentContext) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{1}
}

func (x *AttachmentContext) GetContext() isAttachmentContext_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AttachmentContext) GetTc() *AttachmentContext_TC {
	if x != nil {
		if x, ok := x.Context.(*AttachmentContext_Tc); ok {
			return x.Tc
		}
	}
	return nil
}

type isAttachmentContext_Context interface {
	isAttachmentContext_Context()
}

type AttachmentContext_Tc struct {
	Tc *AttachmentContext_TC `protobuf:"bytes,1,opt,name=tc,proto3,oneof"`
}

func (*AttachmentContext_Tc) isAttachmentContext_Context() {}

// Phase 1: As Cilium loads and prepares a collection for a particular
// attachment point, it sends a PrepareHooksRequest to each plugin with context
// about the attachment point, collection, and local node config. The plugin
// decides which hooks it would like to insert, where it would like to insert
// them, and informs Cilium in the PrepareHooksResponse.
type PrepareHooksRequest struct {
	state             protoimpl.MessageState              `protogen:"open.v1"`
	Collection        *PrepareHooksRequest_CollectionSpec `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	LocalNodeConfig   *LocalNodeConfig                    `protobuf:"bytes,2,opt,name=local_node_config,json=localNodeConfig,proto3" json:"local_node_config,omitempty"`
	AttachmentContext *AttachmentContext                  `protobuf:"bytes,3,opt,name=attachment_context,json=attachmentContext,proto3" json:"attachment_context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareHooksRequest) Reset() {
	*x = PrepareHooksRequest{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHooksRequest) ProtoMessage() {}

func (x *PrepareHooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHooksRequest.ProtoReflect.Descriptor instead.
func (*PrepareHooksRequest) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareHooksRequest) GetCollection() *PrepareHooksRequest_CollectionSpec {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *PrepareHooksRequest) GetLocalNodeConfig() *LocalNodeConfig {
	if x != nil {
		return x.LocalNodeConfig
	}
	return nil
}

func (x *PrepareHooksRequest) GetAttachmentContext() *AttachmentContext {
	if x != nil {
		return x.AttachmentContext
	}
	return nil
}

type PrepareHooksResponse struct {
	state protoimpl.MessageState           `protogen:"open.v1"`
	Hooks []*PrepareHooksResponse_HookSpec `protobuf:"bytes,1,rep,name=hooks,proto3" json:"hooks,omitempty"`
	// May be used by a plugin to associate a LoadHooksRequest with its
	// preceding PrepareHooksRequest or carry other metadata between phases
	// that may be helpful.
	Cookie        string `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareHooksResponse) Reset() {
	*x = PrepareHooksResponse{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHooksResponse) ProtoMessage() {}

func (x *PrepareHooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHooksResponse.ProtoReflect.Descriptor instead.
func (*PrepareHooksResponse) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareHooksResponse) GetHooks() []*PrepareHooksResponse_HookSpec {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *PrepareHooksResponse) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

// Phase 2: Cilium has constructed and loaded the collection along with any
// dispatcher programs that are meant to replace existing entrypoints in the
// collection. Cilium sends a round of requests to any plugins that wanted to
// inject hooks.
type LoadHooksRequest struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Collection        *LoadHooksRequest_Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	LocalNodeConfig   *LocalNodeConfig             `protobuf:"bytes,2,opt,name=local_node_config,json=localNodeConfig,proto3" json:"local_node_config,omitempty"`
	AttachmentContext *AttachmentContext           `protobuf:"bytes,3,opt,name=attachment_context,json=attachmentContext,proto3" json:"attachment_context,omitempty"`
	Hooks             []*LoadHooksRequest_Hook     `protobuf:"bytes,4,rep,name=hooks,proto3" json:"hooks,omitempty"`
	Cookie            string                       `protobuf:"bytes,5,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoadHooksRequest) Reset() {
	*x = LoadHooksRequest{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHooksRequest) ProtoMessage() {}

func (x *LoadHooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHooksRequest.ProtoReflect.Descriptor instead.
func (*LoadHooksRequest) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{4}
}

func (x *LoadHooksRequest) GetCollection() *LoadHooksRequest_Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *LoadHooksRequest) GetLocalNodeConfig() *LocalNodeConfig {
	if x != nil {
		return x.LocalNodeConfig
	}
	return nil
}

func (x *LoadHooksRequest) GetAttachmentContext() *AttachmentContext {
	if x != nil {
		return x.AttachmentContext
	}
	return nil
}

func (x *LoadHooksRequest) GetHooks() []*LoadHooksRequest_Hook {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *LoadHooksRequest) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

type LoadHooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHooksResponse) Reset() {
	*x = LoadHooksResponse{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHooksResponse) ProtoMessage() {}

func (x *LoadHooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHooksResponse.ProtoReflect.Descriptor instead.
func (*LoadHooksResponse) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{5}
}

type AttachmentContext_TC struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	EpConfig      *AttachmentContext_TC_EndpointConfig `protobuf:"bytes,1,opt,name=ep_config,json=epConfig,proto3" json:"ep_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentContext_TC) Reset() {
	*x = AttachmentContext_TC{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentContext_TC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentContext_TC) ProtoMessage() {}

func (x *AttachmentContext_TC) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentContext_TC.ProtoReflect.Descriptor instead.
func (*AttachmentContext_TC) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AttachmentContext_TC) GetEpConfig() *AttachmentContext_TC_EndpointConfig {
	if x != nil {
		return x.EpConfig
	}
	return nil
}

// Contains endpoint-specific config (IP, MAC, etc.)
type AttachmentContext_TC_EndpointConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentContext_TC_EndpointConfig) Reset() {
	*x = AttachmentContext_TC_EndpointConfig{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentContext_TC_EndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentContext_TC_EndpointConfig) ProtoMessage() {}

func (x *AttachmentContext_TC_EndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentContext_TC_EndpointConfig.ProtoReflect.Descriptor instead.
func (*AttachmentContext_TC_EndpointConfig) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{1, 0, 0}
}

type PrepareHooksRequest_CollectionSpec struct {
	state         protoimpl.MessageState                            `protogen:"open.v1"`
	Programs      []*PrepareHooksRequest_CollectionSpec_ProgramSpec `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareHooksRequest_CollectionSpec) Reset() {
	*x = PrepareHooksRequest_CollectionSpec{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHooksRequest_CollectionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHooksRequest_CollectionSpec) ProtoMessage() {}

func (x *PrepareHooksRequest_CollectionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHooksRequest_CollectionSpec.ProtoReflect.Descriptor instead.
func (*PrepareHooksRequest_CollectionSpec) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PrepareHooksRequest_CollectionSpec) GetPrograms() []*PrepareHooksRequest_CollectionSpec_ProgramSpec {
	if x != nil {
		return x.Programs
	}
	return nil
}

type PrepareHooksRequest_CollectionSpec_ProgramSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareHooksRequest_CollectionSpec_ProgramSpec) Reset() {
	*x = PrepareHooksRequest_CollectionSpec_ProgramSpec{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHooksRequest_CollectionSpec_ProgramSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHooksRequest_CollectionSpec_ProgramSpec) ProtoMessage() {}

func (x *PrepareHooksRequest_CollectionSpec_ProgramSpec) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHooksRequest_CollectionSpec_ProgramSpec.ProtoReflect.Descriptor instead.
func (*PrepareHooksRequest_CollectionSpec_ProgramSpec) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *PrepareHooksRequest_CollectionSpec_ProgramSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PrepareHooksResponse_HookSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PRE/POST (for now)
	Type HookType `protobuf:"varint,1,opt,name=type,proto3,enum=datapathplugins.HookType" json:"type,omitempty"`
	// Which program are we instrumenting?
	Target        string                                              `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Constraints   []*PrepareHooksResponse_HookSpec_OrderingConstraint `protobuf:"bytes,3,rep,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareHooksResponse_HookSpec) Reset() {
	*x = PrepareHooksResponse_HookSpec{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHooksResponse_HookSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHooksResponse_HookSpec) ProtoMessage() {}

func (x *PrepareHooksResponse_HookSpec) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHooksResponse_HookSpec.ProtoReflect.Descriptor instead.
func (*PrepareHooksResponse_HookSpec) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{3, 0}
}

func (x *PrepareHooksResponse_HookSpec) GetType() HookType {
	if x != nil {
		return x.Type
	}
	return HookType_PRE
}

func (x *PrepareHooksResponse_HookSpec) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PrepareHooksResponse_HookSpec) GetConstraints() []*PrepareHooksResponse_HookSpec_OrderingConstraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// An OrderingConstraint is a constraint about where this hook should
// go at this hook point relative to other plugins' hooks.
type PrepareHooksResponse_HookSpec_OrderingConstraint struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	Order         PrepareHooksResponse_HookSpec_OrderingConstraint_Order `protobuf:"varint,1,opt,name=order,proto3,enum=datapathplugins.PrepareHooksResponse_HookSpec_OrderingConstraint_Order" json:"order,omitempty"`
	Plugin        string                                                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareHooksResponse_HookSpec_OrderingConstraint) Reset() {
	*x = PrepareHooksResponse_HookSpec_OrderingConstraint{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHooksResponse_HookSpec_OrderingConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHooksResponse_HookSpec_OrderingConstraint) ProtoMessage() {}

func (x *PrepareHooksResponse_HookSpec_OrderingConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHooksResponse_HookSpec_OrderingConstraint.ProtoReflect.Descriptor instead.
func (*PrepareHooksResponse_HookSpec_OrderingConstraint) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *PrepareHooksResponse_HookSpec_OrderingConstraint) GetOrder() PrepareHooksResponse_HookSpec_OrderingConstraint_Order {
	if x != nil {
		return x.Order
	}
	return PrepareHooksResponse_HookSpec_OrderingConstraint_BEFORE
}

func (x *PrepareHooksResponse_HookSpec_OrderingConstraint) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

// Program and map IDs in the collection
type LoadHooksRequest_Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHooksRequest_Collection) Reset() {
	*x = LoadHooksRequest_Collection{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHooksRequest_Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHooksRequest_Collection) ProtoMessage() {}

func (x *LoadHooksRequest_Collection) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHooksRequest_Collection.ProtoReflect.Descriptor instead.
func (*LoadHooksRequest_Collection) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{4, 0}
}

type LoadHooksRequest_Hook struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Type   HookType               `protobuf:"varint,1,opt,name=type,proto3,enum=datapathplugins.HookType" json:"type,omitempty"`
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Contains target metadata necessary for freplace program load.
	AttachTarget *LoadHooksRequest_Hook_AttachTarget `protobuf:"bytes,3,opt,name=attach_target,json=attachTarget,proto3" json:"attach_target,omitempty"`
	// The plugin must pin the program to this pin path before responding
	// to Cilium.
	PinPath       string `protobuf:"bytes,4,opt,name=pin_path,json=pinPath,proto3" json:"pin_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHooksRequest_Hook) Reset() {
	*x = LoadHooksRequest_Hook{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHooksRequest_Hook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHooksRequest_Hook) ProtoMessage() {}

func (x *LoadHooksRequest_Hook) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHooksRequest_Hook.ProtoReflect.Descriptor instead.
func (*LoadHooksRequest_Hook) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{4, 1}
}

func (x *LoadHooksRequest_Hook) GetType() HookType {
	if x != nil {
		return x.Type
	}
	return HookType_PRE
}

func (x *LoadHooksRequest_Hook) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LoadHooksRequest_Hook) GetAttachTarget() *LoadHooksRequest_Hook_AttachTarget {
	if x != nil {
		return x.AttachTarget
	}
	return nil
}

func (x *LoadHooksRequest_Hook) GetPinPath() string {
	if x != nil {
		return x.PinPath
	}
	return ""
}

type LoadHooksRequest_Hook_AttachTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     uint64                 `protobuf:"varint,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	SubprogName   string                 `protobuf:"bytes,2,opt,name=subprog_name,json=subprogName,proto3" json:"subprog_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHooksRequest_Hook_AttachTarget) Reset() {
	*x = LoadHooksRequest_Hook_AttachTarget{}
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHooksRequest_Hook_AttachTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHooksRequest_Hook_AttachTarget) ProtoMessage() {}

func (x *LoadHooksRequest_Hook_AttachTarget) ProtoReflect() protoreflect.Message {
	mi := &file_datapathplugins_datapathplugins_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHooksRequest_Hook_AttachTarget.ProtoReflect.Descriptor instead.
func (*LoadHooksRequest_Hook_AttachTarget) Descriptor() ([]byte, []int) {
	return file_datapathplugins_datapathplugins_proto_rawDescGZIP(), []int{4, 1, 0}
}

func (x *LoadHooksRequest_Hook_AttachTarget) GetProgramId() uint64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *LoadHooksRequest_Hook_AttachTarget) GetSubprogName() string {
	if x != nil {
		return x.SubprogName
	}
	return ""
}

var File_datapathplugins_datapathplugins_proto protoreflect.FileDescriptor

const file_datapathplugins_datapathplugins_proto_rawDesc = "" +
	"\n" +
	"%datapathplugins/datapathplugins.proto\x12\x0fdatapathplugins\"\x11\n" +
	"\x0fLocalNodeConfig\"\xc2\x01\n" +
	"\x11AttachmentContext\x127\n" +
	"\x02tc\x18\x01 \x01(\v2%.datapathplugins.AttachmentContext.TCH\x00R\x02tc\x1ai\n" +
	"\x02TC\x12Q\n" +
	"\tep_config\x18\x01 \x01(\v24.datapathplugins.AttachmentContext.TC.EndpointConfigR\bepConfig\x1a\x10\n" +
	"\x0eEndpointConfigB\t\n" +
	"\acontext\"\x9e\x03\n" +
	"\x13PrepareHooksRequest\x12S\n" +
	"\n" +
	"collection\x18\x01 \x01(\v23.datapathplugins.PrepareHooksRequest.CollectionSpecR\n" +
	"collection\x12L\n" +
	"\x11local_node_config\x18\x02 \x01(\v2 .datapathplugins.LocalNodeConfigR\x0flocalNodeConfig\x12Q\n" +
	"\x12attachment_context\x18\x03 \x01(\v2\".datapathplugins.AttachmentContextR\x11attachmentContext\x1a\x90\x01\n" +
	"\x0eCollectionSpec\x12[\n" +
	"\bprograms\x18\x01 \x03(\v2?.datapathplugins.PrepareHooksRequest.CollectionSpec.ProgramSpecR\bprograms\x1a!\n" +
	"\vProgramSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xdb\x03\n" +
	"\x14PrepareHooksResponse\x12D\n" +
	"\x05hooks\x18\x01 \x03(\v2..datapathplugins.PrepareHooksResponse.HookSpecR\x05hooks\x12\x16\n" +
	"\x06cookie\x18\x02 \x01(\tR\x06cookie\x1a\xe4\x02\n" +
	"\bHookSpec\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.datapathplugins.HookTypeR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12c\n" +
	"\vconstraints\x18\x03 \x03(\v2A.datapathplugins.PrepareHooksResponse.HookSpec.OrderingConstraintR\vconstraints\x1a\xab\x01\n" +
	"\x12OrderingConstraint\x12]\n" +
	"\x05order\x18\x01 \x01(\x0e2G.datapathplugins.PrepareHooksResponse.HookSpec.OrderingConstraint.OrderR\x05order\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\"\x1e\n" +
	"\x05Order\x12\n" +
	"\n" +
	"\x06BEFORE\x10\x00\x12\t\n" +
	"\x05AFTER\x10\x01\"\xfc\x04\n" +
	"\x10LoadHooksRequest\x12L\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2,.datapathplugins.LoadHooksRequest.CollectionR\n" +
	"collection\x12L\n" +
	"\x11local_node_config\x18\x02 \x01(\v2 .datapathplugins.LocalNodeConfigR\x0flocalNodeConfig\x12Q\n" +
	"\x12attachment_context\x18\x03 \x01(\v2\".datapathplugins.AttachmentContextR\x11attachmentContext\x12<\n" +
	"\x05hooks\x18\x04 \x03(\v2&.datapathplugins.LoadHooksRequest.HookR\x05hooks\x12\x16\n" +
	"\x06cookie\x18\x05 \x01(\tR\x06cookie\x1a\f\n" +
	"\n" +
	"Collection\x1a\x94\x02\n" +
	"\x04Hook\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.datapathplugins.HookTypeR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12X\n" +
	"\rattach_target\x18\x03 \x01(\v23.datapathplugins.LoadHooksRequest.Hook.AttachTargetR\fattachTarget\x12\x19\n" +
	"\bpin_path\x18\x04 \x01(\tR\apinPath\x1aP\n" +
	"\fAttachTarget\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\x04R\tprogramId\x12!\n" +
	"\fsubprog_name\x18\x02 \x01(\tR\vsubprogName\"\x13\n" +
	"\x11LoadHooksResponse*\x1d\n" +
	"\bHookType\x12\a\n" +
	"\x03PRE\x10\x00\x12\b\n" +
	"\x04POST\x10\x012\xc5\x01\n" +
	"\x0eDatapathPlugin\x12]\n" +
	"\fPrepareHooks\x12$.datapathplugins.PrepareHooksRequest\x1a%.datapathplugins.PrepareHooksResponse\"\x00\x12T\n" +
	"\tLoadHooks\x12!.datapathplugins.LoadHooksRequest\x1a\".datapathplugins.LoadHooksResponse\"\x00B1Z/github.com/cilium/cilium/api/v1/datapathpluginsb\x06proto3"

var (
	file_datapathplugins_datapathplugins_proto_rawDescOnce sync.Once
	file_datapathplugins_datapathplugins_proto_rawDescData []byte
)

func file_datapathplugins_datapathplugins_proto_rawDescGZIP() []byte {
	file_datapathplugins_datapathplugins_proto_rawDescOnce.Do(func() {
		file_datapathplugins_datapathplugins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datapathplugins_datapathplugins_proto_rawDesc), len(file_datapathplugins_datapathplugins_proto_rawDesc)))
	})
	return file_datapathplugins_datapathplugins_proto_rawDescData
}

var file_datapathplugins_datapathplugins_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_datapathplugins_datapathplugins_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_datapathplugins_datapathplugins_proto_goTypes = []any{
	(HookType)(0), // 0: datapathplugins.HookType
	(PrepareHooksResponse_HookSpec_OrderingConstraint_Order)(0), // 1: datapathplugins.PrepareHooksResponse.HookSpec.OrderingConstraint.Order
	(*LocalNodeConfig)(nil),                                  // 2: datapathplugins.LocalNodeConfig
	(*AttachmentContext)(nil),                                // 3: datapathplugins.AttachmentContext
	(*PrepareHooksRequest)(nil),                              // 4: datapathplugins.PrepareHooksRequest
	(*PrepareHooksResponse)(nil),                             // 5: datapathplugins.PrepareHooksResponse
	(*LoadHooksRequest)(nil),                                 // 6: datapathplugins.LoadHooksRequest
	(*LoadHooksResponse)(nil),                                // 7: datapathplugins.LoadHooksResponse
	(*AttachmentContext_TC)(nil),                             // 8: datapathplugins.AttachmentContext.TC
	(*AttachmentContext_TC_EndpointConfig)(nil),              // 9: datapathplugins.AttachmentContext.TC.EndpointConfig
	(*PrepareHooksRequest_CollectionSpec)(nil),               // 10: datapathplugins.PrepareHooksRequest.CollectionSpec
	(*PrepareHooksRequest_CollectionSpec_ProgramSpec)(nil),   // 11: datapathplugins.PrepareHooksRequest.CollectionSpec.ProgramSpec
	(*PrepareHooksResponse_HookSpec)(nil),                    // 12: datapathplugins.PrepareHooksResponse.HookSpec
	(*PrepareHooksResponse_HookSpec_OrderingConstraint)(nil), // 13: datapathplugins.PrepareHooksResponse.HookSpec.OrderingConstraint
	(*LoadHooksRequest_Collection)(nil),                      // 14: datapathplugins.LoadHooksRequest.Collection
	(*LoadHooksRequest_Hook)(nil),                            // 15: datapathplugins.LoadHooksRequest.Hook
	(*LoadHooksRequest_Hook_AttachTarget)(nil),               // 16: datapathplugins.LoadHooksRequest.Hook.AttachTarget
}
var file_datapathplugins_datapathplugins_proto_depIdxs = []int32{
	8,  // 0: datapathplugins.AttachmentContext.tc:type_name -> datapathplugins.AttachmentContext.TC
	10, // 1: datapathplugins.PrepareHooksRequest.collection:type_name -> datapathplugins.PrepareHooksRequest.CollectionSpec
	2,  // 2: datapathplugins.PrepareHooksRequest.local_node_config:type_name -> datapathplugins.LocalNodeConfig
	3,  // 3: datapathplugins.PrepareHooksRequest.attachment_context:type_name -> datapathplugins.AttachmentContext
	12, // 4: datapathplugins.PrepareHooksResponse.hooks:type_name -> datapathplugins.PrepareHooksResponse.HookSpec
	14, // 5: datapathplugins.LoadHooksRequest.collection:type_name -> datapathplugins.LoadHooksRequest.Collection
	2,  // 6: datapathplugins.LoadHooksRequest.local_node_config:type_name -> datapathplugins.LocalNodeConfig
	3,  // 7: datapathplugins.LoadHooksRequest.attachment_context:type_name -> datapathplugins.AttachmentContext
	15, // 8: datapathplugins.LoadHooksRequest.hooks:type_name -> datapathplugins.LoadHooksRequest.Hook
	9,  // 9: datapathplugins.AttachmentContext.TC.ep_config:type_name -> datapathplugins.AttachmentContext.TC.EndpointConfig
	11, // 10: datapathplugins.PrepareHooksRequest.CollectionSpec.programs:type_name -> datapathplugins.PrepareHooksRequest.CollectionSpec.ProgramSpec
	0,  // 11: datapathplugins.PrepareHooksResponse.HookSpec.type:type_name -> datapathplugins.HookType
	13, // 12: datapathplugins.PrepareHooksResponse.HookSpec.constraints:type_name -> datapathplugins.PrepareHooksResponse.HookSpec.OrderingConstraint
	1,  // 13: datapathplugins.PrepareHooksResponse.HookSpec.OrderingConstraint.order:type_name -> datapathplugins.PrepareHooksResponse.HookSpec.OrderingConstraint.Order
	0,  // 14: datapathplugins.LoadHooksRequest.Hook.type:type_name -> datapathplugins.HookType
	16, // 15: datapathplugins.LoadHooksRequest.Hook.attach_target:type_name -> datapathplugins.LoadHooksRequest.Hook.AttachTarget
	4,  // 16: datapathplugins.DatapathPlugin.PrepareHooks:input_type -> datapathplugins.PrepareHooksRequest
	6,  // 17: datapathplugins.DatapathPlugin.LoadHooks:input_type -> datapathplugins.LoadHooksRequest
	5,  // 18: datapathplugins.DatapathPlugin.PrepareHooks:output_type -> datapathplugins.PrepareHooksResponse
	7,  // 19: datapathplugins.DatapathPlugin.LoadHooks:output_type -> datapathplugins.LoadHooksResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_datapathplugins_datapathplugins_proto_init() }
func file_datapathplugins_datapathplugins_proto_init() {
	if File_datapathplugins_datapathplugins_proto != nil {
		return
	}
	file_datapathplugins_datapathplugins_proto_msgTypes[1].OneofWrappers = []any{
		(*AttachmentContext_Tc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datapathplugins_datapathplugins_proto_rawDesc), len(file_datapathplugins_datapathplugins_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datapathplugins_datapathplugins_proto_goTypes,
		DependencyIndexes: file_datapathplugins_datapathplugins_proto_depIdxs,
		EnumInfos:         file_datapathplugins_datapathplugins_proto_enumTypes,
		MessageInfos:      file_datapathplugins_datapathplugins_proto_msgTypes,
	}.Build()
	File_datapathplugins_datapathplugins_proto = out.File
	file_datapathplugins_datapathplugins_proto_goTypes = nil
	file_datapathplugins_datapathplugins_proto_depIdxs = nil
}
