// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: datapathplugins/datapathplugins.proto

package datapathplugins

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatapathPlugin_PrepareHooks_FullMethodName = "/datapathplugins.DatapathPlugin/PrepareHooks"
	DatapathPlugin_LoadHooks_FullMethodName    = "/datapathplugins.DatapathPlugin/LoadHooks"
)

// DatapathPluginClient is the client API for DatapathPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatapathPluginClient interface {
	PrepareHooks(ctx context.Context, in *PrepareHooksRequest, opts ...grpc.CallOption) (*PrepareHooksResponse, error)
	LoadHooks(ctx context.Context, in *LoadHooksRequest, opts ...grpc.CallOption) (*LoadHooksResponse, error)
}

type datapathPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDatapathPluginClient(cc grpc.ClientConnInterface) DatapathPluginClient {
	return &datapathPluginClient{cc}
}

func (c *datapathPluginClient) PrepareHooks(ctx context.Context, in *PrepareHooksRequest, opts ...grpc.CallOption) (*PrepareHooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareHooksResponse)
	err := c.cc.Invoke(ctx, DatapathPlugin_PrepareHooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datapathPluginClient) LoadHooks(ctx context.Context, in *LoadHooksRequest, opts ...grpc.CallOption) (*LoadHooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadHooksResponse)
	err := c.cc.Invoke(ctx, DatapathPlugin_LoadHooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatapathPluginServer is the server API for DatapathPlugin service.
// All implementations should embed UnimplementedDatapathPluginServer
// for forward compatibility.
type DatapathPluginServer interface {
	PrepareHooks(context.Context, *PrepareHooksRequest) (*PrepareHooksResponse, error)
	LoadHooks(context.Context, *LoadHooksRequest) (*LoadHooksResponse, error)
}

// UnimplementedDatapathPluginServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatapathPluginServer struct{}

func (UnimplementedDatapathPluginServer) PrepareHooks(context.Context, *PrepareHooksRequest) (*PrepareHooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareHooks not implemented")
}
func (UnimplementedDatapathPluginServer) LoadHooks(context.Context, *LoadHooksRequest) (*LoadHooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadHooks not implemented")
}
func (UnimplementedDatapathPluginServer) testEmbeddedByValue() {}

// UnsafeDatapathPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatapathPluginServer will
// result in compilation errors.
type UnsafeDatapathPluginServer interface {
	mustEmbedUnimplementedDatapathPluginServer()
}

func RegisterDatapathPluginServer(s grpc.ServiceRegistrar, srv DatapathPluginServer) {
	// If the following call panics, it indicates UnimplementedDatapathPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatapathPlugin_ServiceDesc, srv)
}

func _DatapathPlugin_PrepareHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareHooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatapathPluginServer).PrepareHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatapathPlugin_PrepareHooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatapathPluginServer).PrepareHooks(ctx, req.(*PrepareHooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatapathPlugin_LoadHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadHooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatapathPluginServer).LoadHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatapathPlugin_LoadHooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatapathPluginServer).LoadHooks(ctx, req.(*LoadHooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatapathPlugin_ServiceDesc is the grpc.ServiceDesc for DatapathPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatapathPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datapathplugins.DatapathPlugin",
	HandlerType: (*DatapathPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareHooks",
			Handler:    _DatapathPlugin_PrepareHooks_Handler,
		},
		{
			MethodName: "LoadHooks",
			Handler:    _DatapathPlugin_LoadHooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datapathplugins/datapathplugins.proto",
}
