// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package config

// BPFSockTerm is a configuration struct for a Cilium datapath object. Warning:
// do not instantiate directly! Always use [NewBPFSockTerm] to ensure the
// default values configured in the ELF are honored.
type BPFSockTerm struct {
	// IPv4 or IPv6.
	AddressFamily uint8 `config:"address_family"`
	// Destination IPv4 address.
	DestIPv4 uint32 `config:"dest_ipv4"`
	// Destination IPv6 address - first 64 bits.
	DestIPv61 uint64 `config:"dest_ipv6_1"`
	// Destination IPv6 address - second 64 bits.
	DestIPv62 uint64 `config:"dest_ipv6_2"`
	// Destination port.
	DestPort uint16 `config:"dest_port"`
}

func NewBPFSockTerm() *BPFSockTerm {
	return &BPFSockTerm{0x0, 0x0, 0x0, 0x0, 0x0}
}
