// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package config

import (
	"errors"
	"fmt"
	"reflect"
	"strings"
)

var errDuplicateVariable = fmt.Errorf("duplicate variable")

type config interface {
	SizeOf(string) int
}

// Map converts an instance of a Go struct generated by [varsToStruct], or a
// slice of such structs, into a map of configuration values to be passed to
// LoadCollection.
//
// Only struct members with a `config` tag are included. The tag value is used
// as the key in the map, and the map value is the runtime value of the member.
//
// Duplicate variables (e.g. by specifying the same object twice) are not
// allowed.
func Map(obj any) (map[string]any, error) {
	if reflect.ValueOf(obj).Kind() == reflect.Slice {
		return sliceOfStructsToMap(obj)
	}

	return structToMap(obj)
}

func sliceOfStructsToMap(objs any) (map[string]any, error) {
	result := make(map[string]any)
	val := reflect.ValueOf(objs)

	if val.Kind() != reflect.Slice {
		return nil, fmt.Errorf("expected slice, got %T", objs)
	}

	for i := 0; i < val.Len(); i++ {
		elem := val.Index(i).Interface()
		m, err := structToMap(elem)
		if err != nil {
			return nil, fmt.Errorf("config object %T(%d): %w", elem, i, err)
		}

		for name, v := range m {
			if _, ok := result[name]; ok {
				return nil, fmt.Errorf("variable %s (in %T) specified more than once: %w", name, elem, errDuplicateVariable)
			}
			result[name] = v
		}
	}

	return result, nil
}

func structToMap(obj any) (map[string]any, error) {
	typ := reflect.TypeOf(obj)
	val := reflect.ValueOf(obj)

	if typ == nil {
		return nil, errors.New("obj is nil")
	}

	cfg, err := asConfig(val)
	if err != nil {
		return nil, fmt.Errorf("validating type: %w", err)
	}

	if typ.Kind() == reflect.Pointer {
		if val.IsNil() {
			return nil, fmt.Errorf("obj is nil pointer to %T", obj)
		}
		val = val.Elem()
	}

	fields, err := structFields(cfg, val, TagName, nil)
	if err != nil {
		return nil, err
	}

	vars := make(map[string]any, len(fields))
	for _, field := range fields {
		tag := nameFromTag(field.Tag.Get(TagName))
		if tag == "" {
			return nil, fmt.Errorf("field %s has no tag", field.Name)
		}

		if vars[tag] != nil {
			return nil, fmt.Errorf("tag %s on field %s occurs multiple times in object", tag, field.Name)
		}

		vars[tag] = field.value.Interface()
	}

	return vars, nil
}

// structField represents a struct field containing a struct tag.
type structField struct {
	reflect.StructField
	origValue reflect.Value
	value     reflect.Value
}

// structFields recursively gathers all fields of a struct and its nested
// structs that are tagged with the given tag.
func structFields(cfg config, structVal reflect.Value, tag string, visited map[reflect.Type]bool) ([]structField, error) {
	if visited == nil {
		visited = make(map[reflect.Type]bool)
	}

	structType := structVal.Type()
	if structType.Kind() != reflect.Struct {
		return nil, fmt.Errorf("%s is not a struct", structType)
	}

	if visited[structType] {
		return nil, fmt.Errorf("recursion on type %s", structType)
	}

	fields := make([]structField, 0, structType.NumField())
	for i := range structType.NumField() {
		field := structField{
			StructField: structType.Field(i),
			origValue:   structVal.Field(i),
		}

		if !field.StructField.IsExported() {
			continue
		}

		// If the field is tagged, gather it and move on.
		name := nameFromTag(field.Tag.Get(tag))
		sz := cfg.SizeOf(name)
		if name != "" && sz != 0 {
			val, err := castTo(field.origValue.Interface(), sz)
			if err != nil {
				return nil, fmt.Errorf("casting value %s to %d bytes: %w", name, sz, err)
			}
			field.value = reflect.ValueOf(val)
			if err != nil {
				return nil, fmt.Errorf("casting %s to %d byte value: %w", name, sz, err)
			}
			fields = append(fields, field)
			continue
		}

		// If the field does not have an ebpf tag, but is a struct or a pointer
		// to a struct, attempt to gather its fields as well.
		var v reflect.Value
		switch field.Type.Kind() {
		case reflect.Ptr:
			if field.Type.Elem().Kind() != reflect.Struct {
				continue
			}

			if field.origValue.IsNil() {
				return nil, fmt.Errorf("nil pointer to %s.%s", structType, field.StructField.Name)
			}

			// Obtain the destination type of the pointer.
			v = field.origValue.Elem()

		case reflect.Struct:
			// Reference the value's type directly.
			v = field.origValue

		default:
			continue
		}

		inner, err := structFields(cfg, v, tag, visited)
		if err != nil {
			return nil, fmt.Errorf("field %s: %w", field.Name, err)
		}

		fields = append(fields, inner...)
	}

	return fields, nil
}

func asConfig(v reflect.Value) (config, error) {
	val, ok := v.Interface().(config)
	if !ok {
		if v.CanAddr() {
			val, ok = v.Addr().Interface().(config)
		}

		if !ok {
			return nil, fmt.Errorf("not a config: no SizeOf() method")
		}
	}

	return val, nil
}

func castTo(v any, size int) (any, error) {
	switch value := v.(type) {
	case []byte:
		if len(value) != size {
			// lazy initialization if []byte field was never
			// configured
			if value == nil {
				return make([]byte, size), nil
			}

			return nil, fmt.Errorf("[]byte: length should be %d (got %d)", size, len(value))
		}
	case int32:
		switch size {
		case 1:
			val := int8(value)
			if int32(val) == value {
				return val, nil
			}
			return nil, fmt.Errorf("int32: value does not fit into an int8")
		case 2:
			val := int16(value)
			if int32(val) == value {
				return val, nil
			}
			return nil, fmt.Errorf("int32: value does not fit into an int16")
		}
	case uint32:
		switch size {
		case 1:
			val := uint8(value)
			if uint32(val) == value {
				return val, nil
			}
			return nil, fmt.Errorf("uint32: value does not fit into a uint8")
		case 2:
			val := uint16(value)
			if uint32(val) == value {
				return val, nil
			}
			return nil, fmt.Errorf("uint32: value does not fit into a uint16")
		}
	}

	return v, nil
}

// nameFromTag extracts the name= part from a protobuf tag:
// `protobuf:"varint,1,opt,name=allow_icmp_frag_needed,json=allowIcmpFragNeeded,proto3"
func nameFromTag(tag string) string {
	for _, part := range strings.Split(tag, ",") {
		if strings.HasPrefix(part, "name=") {
			return part[len("name="):]
		}
	}

	return ""
}
