// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package config

import (
	"errors"
	"fmt"
	"reflect"
)

const (
	protobufTag = "protobuf"
)

var errDuplicateVariable = fmt.Errorf("duplicate variable")

type configMapper interface {
	Map() (map[string]any, error)
}

// Map converts an instance of a Go struct generated by [varsToStruct], or a
// slice of such structs, into a map of configuration values to be passed to
// LoadCollection.
//
// Only struct members with a `config` tag are included. The tag value is used
// as the key in the map, and the map value is the runtime value of the member.
//
// Duplicate variables (e.g. by specifying the same object twice) are not
// allowed.
func Map(obj any) (map[string]any, error) {
	if reflect.ValueOf(obj).Kind() == reflect.Slice {
		return sliceOfConfigMappersToMap(obj)
	}

	return configMapperToMap(obj)
}

func sliceOfConfigMappersToMap(objs any) (map[string]any, error) {
	result := make(map[string]any)
	val := reflect.ValueOf(objs)

	if val.Kind() != reflect.Slice {
		return nil, fmt.Errorf("expected slice, got %T", objs)
	}

	for i := 0; i < val.Len(); i++ {
		elem := val.Index(i).Interface()
		m, err := configMapperToMap(elem)
		if err != nil {
			return nil, fmt.Errorf("config object %T(%d): %w", elem, i, err)
		}

		for name, v := range m {
			if _, ok := result[name]; ok {
				return nil, fmt.Errorf("variable %s (in %T) specified more than once: %w", name, elem, errDuplicateVariable)
			}
			result[name] = v
		}
	}

	return result, nil
}

func configMapperToMap(obj any) (map[string]any, error) {
	cm, ok := obj.(configMapper)
	if !ok {
		return nil, errors.New("does not implement configMapper interface")
	}

	return cm.Map()
}
