// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package testprogs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadPlugins returns the embedded CollectionSpec for Plugins.
func LoadPlugins() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PluginsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Plugins: %w", err)
	}

	return spec, err
}

// LoadPluginsObjects loads Plugins and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PluginsObjects
//	*PluginsPrograms
//	*PluginsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPluginsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPlugins()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PluginsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PluginsSpecs struct {
	PluginsProgramSpecs
	PluginsMapSpecs
	PluginsVariableSpecs
}

// PluginsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PluginsProgramSpecs struct {
	ProgramA *ebpf.ProgramSpec `ebpf:"program_a"`
	ProgramB *ebpf.ProgramSpec `ebpf:"program_b"`
}

// PluginsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PluginsMapSpecs struct {
}

// PluginsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PluginsVariableSpecs struct {
	A_seq *ebpf.VariableSpec `ebpf:"a_seq"`
	B_seq *ebpf.VariableSpec `ebpf:"b_seq"`
	I     *ebpf.VariableSpec `ebpf:"i"`
}

// PluginsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPluginsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PluginsObjects struct {
	PluginsPrograms
	PluginsMaps
	PluginsVariables
}

func (o *PluginsObjects) Close() error {
	return _PluginsClose(
		&o.PluginsPrograms,
		&o.PluginsMaps,
	)
}

// PluginsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPluginsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PluginsMaps struct {
}

func (m *PluginsMaps) Close() error {
	return _PluginsClose()
}

// PluginsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPluginsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PluginsVariables struct {
	A_seq *ebpf.Variable `ebpf:"a_seq"`
	B_seq *ebpf.Variable `ebpf:"b_seq"`
	I     *ebpf.Variable `ebpf:"i"`
}

// PluginsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPluginsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PluginsPrograms struct {
	ProgramA *ebpf.Program `ebpf:"program_a"`
	ProgramB *ebpf.Program `ebpf:"program_b"`
}

func (p *PluginsPrograms) Close() error {
	return _PluginsClose(
		p.ProgramA,
		p.ProgramB,
	)
}

func _PluginsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed plugins_bpfeb.o
var _PluginsBytes []byte
