// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type hostMacaddr struct {
	_    structs.HostLayout
	Addr [6]uint8
	_    [2]byte
}

// loadHost returns the embedded CollectionSpec for host.
func loadHost() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HostBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load host: %w", err)
	}

	return spec, err
}

// loadHostObjects loads host and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hostObjects
//	*hostPrograms
//	*hostMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHostObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHost()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hostSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostSpecs struct {
	hostProgramSpecs
	hostMapSpecs
	hostVariableSpecs
}

// hostProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostProgramSpecs struct {
	BeforeCilFromNetdev *ebpf.ProgramSpec `ebpf:"before_cil_from_netdev"`
}

// hostMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostMapSpecs struct {
	Ifindices *ebpf.MapSpec `ebpf:"ifindices"`
	Ifmacs    *ebpf.MapSpec `ebpf:"ifmacs"`
}

// hostVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostVariableSpecs struct {
	ConfigTunnelPort     *ebpf.VariableSpec `ebpf:"__config_tunnel_port"`
	ConfigTunnelProtocol *ebpf.VariableSpec `ebpf:"__config_tunnel_protocol"`
}

// hostObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHostObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostObjects struct {
	hostPrograms
	hostMaps
	hostVariables
}

func (o *hostObjects) Close() error {
	return _HostClose(
		&o.hostPrograms,
		&o.hostMaps,
	)
}

// hostMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHostObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostMaps struct {
	Ifindices *ebpf.Map `ebpf:"ifindices"`
	Ifmacs    *ebpf.Map `ebpf:"ifmacs"`
}

func (m *hostMaps) Close() error {
	return _HostClose(
		m.Ifindices,
		m.Ifmacs,
	)
}

// hostVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHostObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostVariables struct {
	ConfigTunnelPort     *ebpf.Variable `ebpf:"__config_tunnel_port"`
	ConfigTunnelProtocol *ebpf.Variable `ebpf:"__config_tunnel_protocol"`
}

// hostPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHostObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostPrograms struct {
	BeforeCilFromNetdev *ebpf.Program `ebpf:"before_cil_from_netdev"`
}

func (p *hostPrograms) Close() error {
	return _HostClose(
		p.BeforeCilFromNetdev,
	)
}

func _HostClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed host_bpfeb.o
var _HostBytes []byte
