// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type proxyMacaddr struct {
	_    structs.HostLayout
	Addr [6]uint8
	_    [2]byte
}

// loadProxy returns the embedded CollectionSpec for proxy.
func loadProxy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProxyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load proxy: %w", err)
	}

	return spec, err
}

// loadProxyObjects loads proxy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*proxyObjects
//	*proxyPrograms
//	*proxyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProxyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProxy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// proxySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proxySpecs struct {
	proxyProgramSpecs
	proxyMapSpecs
	proxyVariableSpecs
}

// proxyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proxyProgramSpecs struct {
	BeforeCilFromContainer *ebpf.ProgramSpec `ebpf:"before_cil_from_container"`
}

// proxyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proxyMapSpecs struct {
	Ifindices *ebpf.MapSpec `ebpf:"ifindices"`
	Ifmacs    *ebpf.MapSpec `ebpf:"ifmacs"`
}

// proxyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proxyVariableSpecs struct {
	ConfigTunnelPort     *ebpf.VariableSpec `ebpf:"__config_tunnel_port"`
	ConfigTunnelProtocol *ebpf.VariableSpec `ebpf:"__config_tunnel_protocol"`
	NetkitEnabled        *ebpf.VariableSpec `ebpf:"netkit_enabled"`
}

// proxyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type proxyObjects struct {
	proxyPrograms
	proxyMaps
	proxyVariables
}

func (o *proxyObjects) Close() error {
	return _ProxyClose(
		&o.proxyPrograms,
		&o.proxyMaps,
	)
}

// proxyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type proxyMaps struct {
	Ifindices *ebpf.Map `ebpf:"ifindices"`
	Ifmacs    *ebpf.Map `ebpf:"ifmacs"`
}

func (m *proxyMaps) Close() error {
	return _ProxyClose(
		m.Ifindices,
		m.Ifmacs,
	)
}

// proxyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type proxyVariables struct {
	ConfigTunnelPort     *ebpf.Variable `ebpf:"__config_tunnel_port"`
	ConfigTunnelProtocol *ebpf.Variable `ebpf:"__config_tunnel_protocol"`
	NetkitEnabled        *ebpf.Variable `ebpf:"netkit_enabled"`
}

// proxyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type proxyPrograms struct {
	BeforeCilFromContainer *ebpf.Program `ebpf:"before_cil_from_container"`
}

func (p *proxyPrograms) Close() error {
	return _ProxyClose(
		p.BeforeCilFromContainer,
	)
}

func _ProxyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed proxy_bpfel.o
var _ProxyBytes []byte
