// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type workloadMacaddr struct {
	_    structs.HostLayout
	Addr [6]uint8
	_    [2]byte
}

// loadWorkload returns the embedded CollectionSpec for workload.
func loadWorkload() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_WorkloadBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load workload: %w", err)
	}

	return spec, err
}

// loadWorkloadObjects loads workload and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*workloadObjects
//	*workloadPrograms
//	*workloadMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadWorkloadObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadWorkload()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// workloadSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type workloadSpecs struct {
	workloadProgramSpecs
	workloadMapSpecs
	workloadVariableSpecs
}

// workloadProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type workloadProgramSpecs struct {
	BeforeCilFromContainer *ebpf.ProgramSpec `ebpf:"before_cil_from_container"`
}

// workloadMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type workloadMapSpecs struct {
	Ifindices *ebpf.MapSpec `ebpf:"ifindices"`
	Ifmacs    *ebpf.MapSpec `ebpf:"ifmacs"`
}

// workloadVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type workloadVariableSpecs struct {
	ConfigTunnelPort     *ebpf.VariableSpec `ebpf:"__config_tunnel_port"`
	ConfigTunnelProtocol *ebpf.VariableSpec `ebpf:"__config_tunnel_protocol"`
	InterfaceMac         *ebpf.VariableSpec `ebpf:"interface_mac"`
}

// workloadObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadWorkloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type workloadObjects struct {
	workloadPrograms
	workloadMaps
	workloadVariables
}

func (o *workloadObjects) Close() error {
	return _WorkloadClose(
		&o.workloadPrograms,
		&o.workloadMaps,
	)
}

// workloadMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadWorkloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type workloadMaps struct {
	Ifindices *ebpf.Map `ebpf:"ifindices"`
	Ifmacs    *ebpf.Map `ebpf:"ifmacs"`
}

func (m *workloadMaps) Close() error {
	return _WorkloadClose(
		m.Ifindices,
		m.Ifmacs,
	)
}

// workloadVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadWorkloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type workloadVariables struct {
	ConfigTunnelPort     *ebpf.Variable `ebpf:"__config_tunnel_port"`
	ConfigTunnelProtocol *ebpf.Variable `ebpf:"__config_tunnel_protocol"`
	InterfaceMac         *ebpf.Variable `ebpf:"interface_mac"`
}

// workloadPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadWorkloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type workloadPrograms struct {
	BeforeCilFromContainer *ebpf.Program `ebpf:"before_cil_from_container"`
}

func (p *workloadPrograms) Close() error {
	return _WorkloadClose(
		p.BeforeCilFromContainer,
	)
}

func _WorkloadClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed workload_bpfel.o
var _WorkloadBytes []byte
