//go:build kubernetes_protomessage_one_more_release
// +build kubernetes_protomessage_one_more_release

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by go-to-protobuf. DO NOT EDIT.

package latest

func (*BPFHost) ProtoMessage() {}

func (*BPFLXC) ProtoMessage() {}

func (*BPFOverlay) ProtoMessage() {}

func (*BPFSock) ProtoMessage() {}

func (*BPFWireguard) ProtoMessage() {}

func (*BPFXDP) ProtoMessage() {}

func (*Node) ProtoMessage() {}
