// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package latest

import "fmt"

// BPFHost is a configuration struct for a Cilium datapath object. Warning: do
// not instantiate directly! Always use [NewBPFHost] to ensure the default
// values configured in the ELF are honored.
type BPFHost struct {
	// Allow ICMP_FRAG_NEEDED messages when applying Network Policy.
	AllowICMPFragNeeded bool `config:"allow_icmp_frag_needed,1" protobuf:"bool,1,opt,name=allow_icmp_frag_needed"`
	// MTU of the device the bpf program is attached to (default: MTU set in
	// node_config.h by agent).
	DeviceMTU uint32 `config:"device_mtu,2" protobuf:"varint,2,opt,name=device_mtu"`
	// Respond to ARP requests from local containers to resolve the default
	// gateway.
	EnableARPResponder bool `config:"enable_arp_responder,1" protobuf:"bool,3,opt,name=enable_arp_responder"`
	// Pass traffic with extended IP protocols.
	EnableExtendedIPProtocols bool `config:"enable_extended_ip_protocols,1" protobuf:"bool,4,opt,name=enable_extended_ip_protocols"`
	// Apply Network Policy for ICMP packets.
	EnableICMPRule bool `config:"enable_icmp_rule,1" protobuf:"bool,5,opt,name=enable_icmp_rule"`
	// Enable IPv4 fragments tracking.
	EnableIPv4Fragments bool `config:"enable_ipv4_fragments,1" protobuf:"bool,6,opt,name=enable_ipv4_fragments"`
	// Enable IPv6 fragments tracking.
	EnableIPv6Fragments bool `config:"enable_ipv6_fragments,1" protobuf:"bool,7,opt,name=enable_ipv6_fragments"`
	// Enable L2 Announcements.
	EnableL2Announcements bool `config:"enable_l2_announcements,1" protobuf:"bool,8,opt,name=enable_l2_announcements"`
	// Use netkit devices for pods.
	EnableNetkit bool `config:"enable_netkit,1" protobuf:"bool,9,opt,name=enable_netkit"`
	// Enable routes when service has 0 endpoints.
	EnableNoServiceEndpointsRoutable bool `config:"enable_no_service_endpoints_routable,1" protobuf:"bool,10,opt,name=enable_no_service_endpoints_routable"`
	// Maintain packet and byte counters for every policy entry.
	EnablePolicyAccounting bool `config:"enable_policy_accounting,1" protobuf:"bool,11,opt,name=enable_policy_accounting"`
	// Masquerade traffic to remote nodes.
	EnableRemoteNodeMasquerade bool `config:"enable_remote_node_masquerade,1" protobuf:"bool,12,opt,name=enable_remote_node_masquerade"`
	// Ephemeral port range minimun.
	EphemeralMin uint32 `config:"ephemeral_min,2" protobuf:"varint,13,opt,name=ephemeral_min"`
	// Length of the Ethernet header on this device. May be set to zero on L2-less
	// devices. (default __ETH_HLEN).
	EthHeaderLength uint32 `config:"eth_header_length,1" protobuf:"varint,14,opt,name=eth_header_length"`
	// The host endpoint ID.
	HostEPID uint32 `config:"host_ep_id,2" protobuf:"varint,15,opt,name=host_ep_id"`
	// Enable hybrid mode routing based on subnet IDs.
	HybridRoutingEnabled bool `config:"hybrid_routing_enabled,1" protobuf:"bool,16,opt,name=hybrid_routing_enabled"`
	// Ifindex of the interface the bpf program is attached to.
	InterfaceIfIndex uint32 `config:"interface_ifindex,4" protobuf:"varint,17,opt,name=interface_ifindex"`
	// MAC address of the interface the bpf program is attached to.
	InterfaceMAC []byte `config:"interface_mac,8" protobuf:"bytes,18,opt,name=interface_mac"`
	// If the agent is down for longer than the lease duration, stop responding.
	L2AnnouncementsMaxLiveness uint64 `config:"l2_announcements_max_liveness,8" protobuf:"varint,19,opt,name=l2_announcements_max_liveness"`
	// Masquerade address for IPv4 traffic.
	NATIPv4Masquerade []byte `config:"nat_ipv4_masquerade,4" protobuf:"bytes,20,opt,name=nat_ipv4_masquerade"`
	// Masquerade address for IPv6 traffic.
	NATIPv6Masquerade []byte `config:"nat_ipv6_masquerade,16" protobuf:"bytes,21,opt,name=nat_ipv6_masquerade"`
	// Whether to redirect to the proxy via cilium_net (hairpin) or via stack.
	ProxyRedirectViaCiliumNet bool `config:"proxy_redirect_via_cilium_net,1" protobuf:"bool,22,opt,name=proxy_redirect_via_cilium_net"`
	// The endpoint's security label.
	SecurityLabel uint32 `config:"security_label,4" protobuf:"varint,23,opt,name=security_label"`
	// Port number used for the overlay network.
	TunnelPort uint32 `config:"tunnel_port,2" protobuf:"varint,24,opt,name=tunnel_port"`
	// The identifier of the tunnel protocol used for the overlay network.
	TunnelProtocol uint32 `config:"tunnel_protocol,1" protobuf:"varint,25,opt,name=tunnel_protocol"`
	// VXLAN tunnel endpoint network mask.
	VTEPMask uint32 `config:"vtep_mask,4" protobuf:"varint,26,opt,name=vtep_mask"`
	// Index of the WireGuard interface.
	WGIfIndex uint32 `config:"wg_ifindex,4" protobuf:"varint,27,opt,name=wg_ifindex"`
	// Port for the WireGuard interface.
	WGPort uint32 `config:"wg_port,2" protobuf:"varint,28,opt,name=wg_port"`

	Node `protobuf:"bytes,29,opt,name=node"`
}

func NewBPFHost(node Node) *BPFHost {
	return &BPFHost{false, 0x5dc, false, false, false, false, false, false, false,
		false, false, false, 0x0, 0xe, 0x0, false, 0x0, []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		0x0, []byte{0x0, 0x0, 0x0, 0x0},
		[]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		false, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, node}
}

func (c *BPFHost) Map() (map[string]any, error) {
	result := make(map[string]any)
	mapNode, err := c.Node.Map()
	if err != nil {
		return nil, fmt.Errorf("Node: %w", err)
	}
	for name, val := range mapNode {
		if _, ok := result[name]; ok {
			return nil, fmt.Errorf("Node: %s exists in two embedded types", name)
		}
		result[name] = val
	}
	result["allow_icmp_frag_needed"] = c.AllowICMPFragNeeded
	DeviceMTU := uint16(c.DeviceMTU)
	if uint32(DeviceMTU) != c.DeviceMTU {
		return nil, fmt.Errorf("DeviceMTU must fit into a uint16 (value = %d)", c.DeviceMTU)
	}
	result["device_mtu"] = DeviceMTU
	result["enable_arp_responder"] = c.EnableARPResponder
	result["enable_extended_ip_protocols"] = c.EnableExtendedIPProtocols
	result["enable_icmp_rule"] = c.EnableICMPRule
	result["enable_ipv4_fragments"] = c.EnableIPv4Fragments
	result["enable_ipv6_fragments"] = c.EnableIPv6Fragments
	result["enable_l2_announcements"] = c.EnableL2Announcements
	result["enable_netkit"] = c.EnableNetkit
	result["enable_no_service_endpoints_routable"] = c.EnableNoServiceEndpointsRoutable
	result["enable_policy_accounting"] = c.EnablePolicyAccounting
	result["enable_remote_node_masquerade"] = c.EnableRemoteNodeMasquerade
	EphemeralMin := uint16(c.EphemeralMin)
	if uint32(EphemeralMin) != c.EphemeralMin {
		return nil, fmt.Errorf("EphemeralMin must fit into a uint16 (value = %d)", c.EphemeralMin)
	}
	result["ephemeral_min"] = EphemeralMin
	EthHeaderLength := uint8(c.EthHeaderLength)
	if uint32(EthHeaderLength) != c.EthHeaderLength {
		return nil, fmt.Errorf("EthHeaderLength must fit into a uint8 (value = %d)", c.EthHeaderLength)
	}
	result["eth_header_length"] = EthHeaderLength
	HostEPID := uint16(c.HostEPID)
	if uint32(HostEPID) != c.HostEPID {
		return nil, fmt.Errorf("HostEPID must fit into a uint16 (value = %d)", c.HostEPID)
	}
	result["host_ep_id"] = HostEPID
	result["hybrid_routing_enabled"] = c.HybridRoutingEnabled
	result["interface_ifindex"] = c.InterfaceIfIndex
	if len(c.InterfaceMAC) != 8 {
		return nil, fmt.Errorf("InterfaceMAC must be 8 bytes (got %d)", len(c.InterfaceMAC))
	}
	InterfaceMAC := [8]byte{}
	copy(InterfaceMAC[:], c.InterfaceMAC)
	result["interface_mac"] = InterfaceMAC
	result["l2_announcements_max_liveness"] = c.L2AnnouncementsMaxLiveness
	if len(c.NATIPv4Masquerade) != 4 {
		return nil, fmt.Errorf("NATIPv4Masquerade must be 4 bytes (got %d)", len(c.NATIPv4Masquerade))
	}
	NATIPv4Masquerade := [4]byte{}
	copy(NATIPv4Masquerade[:], c.NATIPv4Masquerade)
	result["nat_ipv4_masquerade"] = NATIPv4Masquerade
	if len(c.NATIPv6Masquerade) != 16 {
		return nil, fmt.Errorf("NATIPv6Masquerade must be 16 bytes (got %d)", len(c.NATIPv6Masquerade))
	}
	NATIPv6Masquerade := [16]byte{}
	copy(NATIPv6Masquerade[:], c.NATIPv6Masquerade)
	result["nat_ipv6_masquerade"] = NATIPv6Masquerade
	result["proxy_redirect_via_cilium_net"] = c.ProxyRedirectViaCiliumNet
	result["security_label"] = c.SecurityLabel
	TunnelPort := uint16(c.TunnelPort)
	if uint32(TunnelPort) != c.TunnelPort {
		return nil, fmt.Errorf("TunnelPort must fit into a uint16 (value = %d)", c.TunnelPort)
	}
	result["tunnel_port"] = TunnelPort
	TunnelProtocol := uint8(c.TunnelProtocol)
	if uint32(TunnelProtocol) != c.TunnelProtocol {
		return nil, fmt.Errorf("TunnelProtocol must fit into a uint8 (value = %d)", c.TunnelProtocol)
	}
	result["tunnel_protocol"] = TunnelProtocol
	result["vtep_mask"] = c.VTEPMask
	result["wg_ifindex"] = c.WGIfIndex
	WGPort := uint16(c.WGPort)
	if uint32(WGPort) != c.WGPort {
		return nil, fmt.Errorf("WGPort must fit into a uint16 (value = %d)", c.WGPort)
	}
	result["wg_port"] = WGPort
	return result, nil
}
