// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package latest

import "fmt"

// Node is a configuration struct for a Cilium datapath object. Warning: do not
// instantiate directly! Always use [NewNode] to ensure the default values
// configured in the ELF are honored.
type Node struct {
	// Interface index of the cilium_host device.
	CiliumHostIfIndex uint32 `config:"cilium_host_ifindex,4" protobuf:"varint,1,opt,name=cilium_host_ifindex"`
	// MAC address of the cilium_host device.
	CiliumHostMAC []byte `config:"cilium_host_mac,8" protobuf:"bytes,2,opt,name=cilium_host_mac"`
	// Interface index of the cilium_net device.
	CiliumNetIfIndex uint32 `config:"cilium_net_ifindex,4" protobuf:"varint,3,opt,name=cilium_net_ifindex"`
	// MAC address of the cilium_net device.
	CiliumNetMAC []byte `config:"cilium_net_mac,8" protobuf:"bytes,4,opt,name=cilium_net_mac"`
	// Cluster ID.
	ClusterID uint32 `config:"cluster_id,4" protobuf:"varint,5,opt,name=cluster_id"`
	// Number of bits of the identity reserved for the Cluster ID.
	ClusterIDBits uint32 `config:"cluster_id_bits,4" protobuf:"varint,6,opt,name=cluster_id_bits"`
	// Enable debugging trace statements for load balancer.
	DebugLB bool `config:"debug_lb,1" protobuf:"bool,7,opt,name=debug_lb"`
	// Index of the interface used to connect nodes in the cluster.
	DirectRoutingDevIfIndex uint32 `config:"direct_routing_dev_ifindex,4" protobuf:"varint,8,opt,name=direct_routing_dev_ifindex"`
	// Enable per flow (conntrack) statistics.
	EnableConntrackAccounting bool `config:"enable_conntrack_accounting,1" protobuf:"bool,9,opt,name=enable_conntrack_accounting"`
	// Use jiffies (count of timer ticks since boot).
	EnableJiffies bool `config:"enable_jiffies,1" protobuf:"bool,10,opt,name=enable_jiffies"`
	// Enable BPF-based proxy redirection.
	EnableTproxy bool `config:"enable_tproxy,1" protobuf:"bool,11,opt,name=enable_tproxy"`
	// Cluster-wide IPv4 tuple hash seed sourced.
	HashInit4Seed uint32 `config:"hash_init4_seed,4" protobuf:"varint,12,opt,name=hash_init4_seed"`
	// Cluster-wide IPv6 tuple hash seed sourced.
	HashInit6Seed uint32 `config:"hash_init6_seed,4" protobuf:"varint,13,opt,name=hash_init6_seed"`
	// Number of timer ticks per second.
	KernelHz uint32 `config:"kernel_hz,4" protobuf:"varint,14,opt,name=kernel_hz"`
	// NAT 46x64 prefix.
	NAT46X64Prefix []byte `config:"nat_46x64_prefix,4" protobuf:"bytes,15,opt,name=nat_46x64_prefix"`
	// Nodeport maximum port value.
	NodeportPortMax uint32 `config:"nodeport_port_max,2" protobuf:"varint,16,opt,name=nodeport_port_max"`
	// Nodeport minimum port value.
	NodeportPortMin uint32 `config:"nodeport_port_min,2" protobuf:"varint,17,opt,name=nodeport_port_min"`
	// Enable ICMP responses for policy-denied traffic.
	PolicyDenyResponseEnabled bool `config:"policy_deny_response_enabled,1" protobuf:"bool,18,opt,name=policy_deny_response_enabled"`
	// Internal IPv6 router address assigned to the cilium_host interface.
	RouterIPv6 []byte `config:"router_ipv6,16" protobuf:"bytes,19,opt,name=router_ipv6"`
	// IPv4 source address used for SNAT when a Pod talks to itself over a Service.
	ServiceLoopbackIPv4 []byte `config:"service_loopback_ipv4,4" protobuf:"bytes,20,opt,name=service_loopback_ipv4"`
	// IPv6 source address used for SNAT when a Pod talks to itself over a Service.
	ServiceLoopbackIPv6 []byte `config:"service_loopback_ipv6,16" protobuf:"bytes,21,opt,name=service_loopback_ipv6"`
	// Whether or not BPF_FIB_LOOKUP_SKIP_NEIGH is supported.
	SupportsFIBLookupSkipNeigh bool `config:"supports_fib_lookup_skip_neigh,1" protobuf:"bool,22,opt,name=supports_fib_lookup_skip_neigh"`
	// Length of payload to capture when tracing native packets.
	TracePayloadLen uint32 `config:"trace_payload_len,4" protobuf:"varint,23,opt,name=trace_payload_len"`
	// Length of payload to capture when tracing overlay packets.
	TracePayloadLenOverlay uint32 `config:"trace_payload_len_overlay,4" protobuf:"varint,24,opt,name=trace_payload_len_overlay"`
	// The IP option type to use for packet tracing.
	TracingIPOptionType uint32 `config:"tracing_ip_option_type,1" protobuf:"varint,25,opt,name=tracing_ip_option_type"`
}

func NewNode() *Node {
	return &Node{0x0, []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 0x0, []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		0x0, 0x8, false, 0x0, false, false, false, 0x0, 0x0, 0x0, []byte{0x0, 0x0, 0x0, 0x0},
		0x0, 0x0, false,
		[]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		[]byte{0x0, 0x0, 0x0, 0x0},
		[]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		false, 0x0, 0x0, 0x0}
}

func (c *Node) Map() (map[string]any, error) {
	result := make(map[string]any)
	result["cilium_host_ifindex"] = c.CiliumHostIfIndex
	if len(c.CiliumHostMAC) != 8 {
		return nil, fmt.Errorf("CiliumHostMAC must be 8 bytes (got %d)", len(c.CiliumHostMAC))
	}
	CiliumHostMAC := [8]byte{}
	copy(CiliumHostMAC[:], c.CiliumHostMAC)
	result["cilium_host_mac"] = CiliumHostMAC
	result["cilium_net_ifindex"] = c.CiliumNetIfIndex
	if len(c.CiliumNetMAC) != 8 {
		return nil, fmt.Errorf("CiliumNetMAC must be 8 bytes (got %d)", len(c.CiliumNetMAC))
	}
	CiliumNetMAC := [8]byte{}
	copy(CiliumNetMAC[:], c.CiliumNetMAC)
	result["cilium_net_mac"] = CiliumNetMAC
	result["cluster_id"] = c.ClusterID
	result["cluster_id_bits"] = c.ClusterIDBits
	result["debug_lb"] = c.DebugLB
	result["direct_routing_dev_ifindex"] = c.DirectRoutingDevIfIndex
	result["enable_conntrack_accounting"] = c.EnableConntrackAccounting
	result["enable_jiffies"] = c.EnableJiffies
	result["enable_tproxy"] = c.EnableTproxy
	result["hash_init4_seed"] = c.HashInit4Seed
	result["hash_init6_seed"] = c.HashInit6Seed
	result["kernel_hz"] = c.KernelHz
	if len(c.NAT46X64Prefix) != 4 {
		return nil, fmt.Errorf("NAT46X64Prefix must be 4 bytes (got %d)", len(c.NAT46X64Prefix))
	}
	NAT46X64Prefix := [4]byte{}
	copy(NAT46X64Prefix[:], c.NAT46X64Prefix)
	result["nat_46x64_prefix"] = NAT46X64Prefix
	NodeportPortMax := uint16(c.NodeportPortMax)
	if uint32(NodeportPortMax) != c.NodeportPortMax {
		return nil, fmt.Errorf("NodeportPortMax must fit into a uint16 (value = %d)", c.NodeportPortMax)
	}
	result["nodeport_port_max"] = NodeportPortMax
	NodeportPortMin := uint16(c.NodeportPortMin)
	if uint32(NodeportPortMin) != c.NodeportPortMin {
		return nil, fmt.Errorf("NodeportPortMin must fit into a uint16 (value = %d)", c.NodeportPortMin)
	}
	result["nodeport_port_min"] = NodeportPortMin
	result["policy_deny_response_enabled"] = c.PolicyDenyResponseEnabled
	if len(c.RouterIPv6) != 16 {
		return nil, fmt.Errorf("RouterIPv6 must be 16 bytes (got %d)", len(c.RouterIPv6))
	}
	RouterIPv6 := [16]byte{}
	copy(RouterIPv6[:], c.RouterIPv6)
	result["router_ipv6"] = RouterIPv6
	if len(c.ServiceLoopbackIPv4) != 4 {
		return nil, fmt.Errorf("ServiceLoopbackIPv4 must be 4 bytes (got %d)", len(c.ServiceLoopbackIPv4))
	}
	ServiceLoopbackIPv4 := [4]byte{}
	copy(ServiceLoopbackIPv4[:], c.ServiceLoopbackIPv4)
	result["service_loopback_ipv4"] = ServiceLoopbackIPv4
	if len(c.ServiceLoopbackIPv6) != 16 {
		return nil, fmt.Errorf("ServiceLoopbackIPv6 must be 16 bytes (got %d)", len(c.ServiceLoopbackIPv6))
	}
	ServiceLoopbackIPv6 := [16]byte{}
	copy(ServiceLoopbackIPv6[:], c.ServiceLoopbackIPv6)
	result["service_loopback_ipv6"] = ServiceLoopbackIPv6
	result["supports_fib_lookup_skip_neigh"] = c.SupportsFIBLookupSkipNeigh
	result["trace_payload_len"] = c.TracePayloadLen
	result["trace_payload_len_overlay"] = c.TracePayloadLenOverlay
	TracingIPOptionType := uint8(c.TracingIPOptionType)
	if uint32(TracingIPOptionType) != c.TracingIPOptionType {
		return nil, fmt.Errorf("TracingIPOptionType must fit into a uint8 (value = %d)", c.TracingIPOptionType)
	}
	result["tracing_ip_option_type"] = TracingIPOptionType
	return result, nil
}
