// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package latest

import "fmt"

func NewNode() *Node {
	r := &Node{}
	r.CiliumHostIfindex = 0x0
	r.CiliumHostMac = []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
	r.CiliumNetIfindex = 0x0
	r.CiliumNetMac = []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
	r.ClusterId = 0x0
	r.ClusterIdBits = 0x8
	r.DebugLb = false
	r.DirectRoutingDevIfindex = 0x0
	r.EnableConntrackAccounting = false
	r.EnableJiffies = false
	r.EnableTproxy = false
	r.HashInit4Seed = 0x0
	r.HashInit6Seed = 0x0
	r.KernelHz = 0x0
	r.Nat_46X64Prefix = []byte{0x0, 0x0, 0x0, 0x0}
	r.NodeportPortMax = 0x0
	r.NodeportPortMin = 0x0
	r.PolicyDenyResponseEnabled = false
	r.RouterIpv6 = []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
	r.ServiceLoopbackIpv4 = []byte{0x0, 0x0, 0x0, 0x0}
	r.ServiceLoopbackIpv6 = []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
	r.SupportsFibLookupSkipNeigh = false
	r.TracePayloadLen = 0x0
	r.TracePayloadLenOverlay = 0x0
	r.TracingIpOptionType = 0x0
	return r
}

func (c *Node) Map() (map[string]any, error) {
	result := make(map[string]any)
	result["cilium_host_ifindex"] = c.CiliumHostIfindex
	if (len(c.CiliumHostMac) != 8) {
		return nil, fmt.Errorf("CiliumHostMac must be 8 bytes (got %d)", len(c.CiliumHostMac))
	}
	result["cilium_host_mac"] = c.CiliumHostMac
	result["cilium_net_ifindex"] = c.CiliumNetIfindex
	if (len(c.CiliumNetMac) != 8) {
		return nil, fmt.Errorf("CiliumNetMac must be 8 bytes (got %d)", len(c.CiliumNetMac))
	}
	result["cilium_net_mac"] = c.CiliumNetMac
	result["cluster_id"] = c.ClusterId
	result["cluster_id_bits"] = c.ClusterIdBits
	result["debug_lb"] = c.DebugLb
	result["direct_routing_dev_ifindex"] = c.DirectRoutingDevIfindex
	result["enable_conntrack_accounting"] = c.EnableConntrackAccounting
	result["enable_jiffies"] = c.EnableJiffies
	result["enable_tproxy"] = c.EnableTproxy
	result["hash_init4_seed"] = c.HashInit4Seed
	result["hash_init6_seed"] = c.HashInit6Seed
	result["kernel_hz"] = c.KernelHz
	if (len(c.Nat_46X64Prefix) != 4) {
		return nil, fmt.Errorf("Nat_46X64Prefix must be 4 bytes (got %d)", len(c.Nat_46X64Prefix))
	}
	result["nat_46x64_prefix"] = c.Nat_46X64Prefix
	NodeportPortMax := uint16(c.NodeportPortMax)
	if (uint32(NodeportPortMax) != c.NodeportPortMax) {
		return nil, fmt.Errorf("NodeportPortMax must fit into a uint16 (value = %d)", c.NodeportPortMax)
	}
	result["nodeport_port_max"] = NodeportPortMax
	NodeportPortMin := uint16(c.NodeportPortMin)
	if (uint32(NodeportPortMin) != c.NodeportPortMin) {
		return nil, fmt.Errorf("NodeportPortMin must fit into a uint16 (value = %d)", c.NodeportPortMin)
	}
	result["nodeport_port_min"] = NodeportPortMin
	result["policy_deny_response_enabled"] = c.PolicyDenyResponseEnabled
	if (len(c.RouterIpv6) != 16) {
		return nil, fmt.Errorf("RouterIpv6 must be 16 bytes (got %d)", len(c.RouterIpv6))
	}
	result["router_ipv6"] = c.RouterIpv6
	if (len(c.ServiceLoopbackIpv4) != 4) {
		return nil, fmt.Errorf("ServiceLoopbackIpv4 must be 4 bytes (got %d)", len(c.ServiceLoopbackIpv4))
	}
	result["service_loopback_ipv4"] = c.ServiceLoopbackIpv4
	if (len(c.ServiceLoopbackIpv6) != 16) {
		return nil, fmt.Errorf("ServiceLoopbackIpv6 must be 16 bytes (got %d)", len(c.ServiceLoopbackIpv6))
	}
	result["service_loopback_ipv6"] = c.ServiceLoopbackIpv6
	result["supports_fib_lookup_skip_neigh"] = c.SupportsFibLookupSkipNeigh
	result["trace_payload_len"] = c.TracePayloadLen
	result["trace_payload_len_overlay"] = c.TracePayloadLenOverlay
	TracingIpOptionType := uint8(c.TracingIpOptionType)
	if (uint32(TracingIpOptionType) != c.TracingIpOptionType) {
		return nil, fmt.Errorf("TracingIpOptionType must fit into a uint8 (value = %d)", c.TracingIpOptionType)
	}
	result["tracing_ip_option_type"] = TracingIpOptionType
	return result, nil
}
