// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package latest

import "fmt"

// BPFSock is a configuration struct for a Cilium datapath object. Warning: do
// not instantiate directly! Always use [NewBPFSock] to ensure the default
// values configured in the ELF are honored.
type BPFSock struct {
	// Pass traffic with extended IP protocols.
	EnableExtendedIPProtocols bool `config:"enable_extended_ip_protocols,1" protobuf:"bool,1,opt,name=enable_extended_ip_protocols"`
	// Enable IPv4 fragments tracking.
	EnableIPv4Fragments bool `config:"enable_ipv4_fragments,1" protobuf:"bool,2,opt,name=enable_ipv4_fragments"`
	// Enable IPv6 fragments tracking.
	EnableIPv6Fragments bool `config:"enable_ipv6_fragments,1" protobuf:"bool,3,opt,name=enable_ipv6_fragments"`
	// Enable support for Local Redirect Policy.
	EnableLRP bool `config:"enable_lrp,1" protobuf:"bool,4,opt,name=enable_lrp"`
	// Enable routes when service has 0 endpoints.
	EnableNoServiceEndpointsRoutable bool `config:"enable_no_service_endpoints_routable,1" protobuf:"bool,5,opt,name=enable_no_service_endpoints_routable"`
	// Port number used for the overlay network.
	TunnelPort uint32 `config:"tunnel_port,2" protobuf:"varint,6,opt,name=tunnel_port"`
	// The identifier of the tunnel protocol used for the overlay network.
	TunnelProtocol uint32 `config:"tunnel_protocol,1" protobuf:"varint,7,opt,name=tunnel_protocol"`

	Node `protobuf:"bytes,8,opt,name=node"`
}

func NewBPFSock(node Node) *BPFSock {
	return &BPFSock{false, false, false, false, false, 0x0, 0x0, node}
}

func (c *BPFSock) Map() (map[string]any, error) {
	result := make(map[string]any)
	mapNode, err := c.Node.Map()
	if err != nil {
		return nil, fmt.Errorf("Node: %w", err)
	}
	for name, val := range mapNode {
		if _, ok := result[name]; ok {
			return nil, fmt.Errorf("Node: %s exists in two embedded types", name)
		}
		result[name] = val
	}
	result["enable_extended_ip_protocols"] = c.EnableExtendedIPProtocols
	result["enable_ipv4_fragments"] = c.EnableIPv4Fragments
	result["enable_ipv6_fragments"] = c.EnableIPv6Fragments
	result["enable_lrp"] = c.EnableLRP
	result["enable_no_service_endpoints_routable"] = c.EnableNoServiceEndpointsRoutable
	TunnelPort := uint16(c.TunnelPort)
	if uint32(TunnelPort) != c.TunnelPort {
		return nil, fmt.Errorf("TunnelPort must fit into a uint16 (value = %d)", c.TunnelPort)
	}
	result["tunnel_port"] = TunnelPort
	TunnelProtocol := uint8(c.TunnelProtocol)
	if uint32(TunnelProtocol) != c.TunnelProtocol {
		return nil, fmt.Errorf("TunnelProtocol must fit into a uint8 (value = %d)", c.TunnelProtocol)
	}
	result["tunnel_protocol"] = TunnelProtocol
	return result, nil
}
