// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package latest

import "fmt"

// BPFWireguard is a configuration struct for a Cilium datapath object. Warning:
// do not instantiate directly! Always use [NewBPFWireguard] to ensure the
// default values configured in the ELF are honored.
type BPFWireguard struct {
	// MTU of the device the bpf program is attached to (default: MTU set in
	// node_config.h by agent).
	DeviceMTU uint32 `config:"device_mtu,2" protobuf:"varint,1,opt,name=device_mtu"`
	// Pass traffic with extended IP protocols.
	EnableExtendedIPProtocols bool `config:"enable_extended_ip_protocols,1" protobuf:"bool,2,opt,name=enable_extended_ip_protocols"`
	// Enable IPv4 fragments tracking.
	EnableIPv4Fragments bool `config:"enable_ipv4_fragments,1" protobuf:"bool,3,opt,name=enable_ipv4_fragments"`
	// Enable IPv6 fragments tracking.
	EnableIPv6Fragments bool `config:"enable_ipv6_fragments,1" protobuf:"bool,4,opt,name=enable_ipv6_fragments"`
	// Use netkit devices for pods.
	EnableNetkit bool `config:"enable_netkit,1" protobuf:"bool,5,opt,name=enable_netkit"`
	// Enable routes when service has 0 endpoints.
	EnableNoServiceEndpointsRoutable bool `config:"enable_no_service_endpoints_routable,1" protobuf:"bool,6,opt,name=enable_no_service_endpoints_routable"`
	// Masquerade traffic to remote nodes.
	EnableRemoteNodeMasquerade bool `config:"enable_remote_node_masquerade,1" protobuf:"bool,7,opt,name=enable_remote_node_masquerade"`
	// Ephemeral port range minimun.
	EphemeralMin uint32 `config:"ephemeral_min,2" protobuf:"varint,8,opt,name=ephemeral_min"`
	// Ifindex of the interface the bpf program is attached to.
	InterfaceIfIndex uint32 `config:"interface_ifindex,4" protobuf:"varint,9,opt,name=interface_ifindex"`
	// MAC address of the interface the bpf program is attached to.
	InterfaceMAC []byte `config:"interface_mac,8" protobuf:"bytes,10,opt,name=interface_mac"`
	// Masquerade address for IPv4 traffic.
	NATIPv4Masquerade []byte `config:"nat_ipv4_masquerade,4" protobuf:"bytes,11,opt,name=nat_ipv4_masquerade"`
	// Masquerade address for IPv6 traffic.
	NATIPv6Masquerade []byte `config:"nat_ipv6_masquerade,16" protobuf:"bytes,12,opt,name=nat_ipv6_masquerade"`
	// Whether to redirect to the proxy via cilium_net (hairpin) or via stack.
	ProxyRedirectViaCiliumNet bool `config:"proxy_redirect_via_cilium_net,1" protobuf:"bool,13,opt,name=proxy_redirect_via_cilium_net"`
	// Port number used for the overlay network.
	TunnelPort uint32 `config:"tunnel_port,2" protobuf:"varint,14,opt,name=tunnel_port"`
	// The identifier of the tunnel protocol used for the overlay network.
	TunnelProtocol uint32 `config:"tunnel_protocol,1" protobuf:"varint,15,opt,name=tunnel_protocol"`

	Node `protobuf:"bytes,16,opt,name=node"`
}

func NewBPFWireguard(node Node) *BPFWireguard {
	return &BPFWireguard{0x5dc, false, false, false, false, false, false, 0x0, 0x0, []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		[]byte{0x0, 0x0, 0x0, 0x0},
		[]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		false, 0x0, 0x0, node}
}

func (c *BPFWireguard) Map() (map[string]any, error) {
	result := make(map[string]any)
	mapNode, err := c.Node.Map()
	if err != nil {
		return nil, fmt.Errorf("Node: %w", err)
	}
	for name, val := range mapNode {
		if _, ok := result[name]; ok {
			return nil, fmt.Errorf("Node: %s exists in two embedded types", name)
		}
		result[name] = val
	}
	DeviceMTU := uint16(c.DeviceMTU)
	if uint32(DeviceMTU) != c.DeviceMTU {
		return nil, fmt.Errorf("DeviceMTU must fit into a uint16 (value = %d)", c.DeviceMTU)
	}
	result["device_mtu"] = DeviceMTU
	result["enable_extended_ip_protocols"] = c.EnableExtendedIPProtocols
	result["enable_ipv4_fragments"] = c.EnableIPv4Fragments
	result["enable_ipv6_fragments"] = c.EnableIPv6Fragments
	result["enable_netkit"] = c.EnableNetkit
	result["enable_no_service_endpoints_routable"] = c.EnableNoServiceEndpointsRoutable
	result["enable_remote_node_masquerade"] = c.EnableRemoteNodeMasquerade
	EphemeralMin := uint16(c.EphemeralMin)
	if uint32(EphemeralMin) != c.EphemeralMin {
		return nil, fmt.Errorf("EphemeralMin must fit into a uint16 (value = %d)", c.EphemeralMin)
	}
	result["ephemeral_min"] = EphemeralMin
	result["interface_ifindex"] = c.InterfaceIfIndex
	if len(c.InterfaceMAC) != 8 {
		return nil, fmt.Errorf("InterfaceMAC must be 8 bytes (got %d)", len(c.InterfaceMAC))
	}
	InterfaceMAC := [8]byte{}
	copy(InterfaceMAC[:], c.InterfaceMAC)
	result["interface_mac"] = InterfaceMAC
	if len(c.NATIPv4Masquerade) != 4 {
		return nil, fmt.Errorf("NATIPv4Masquerade must be 4 bytes (got %d)", len(c.NATIPv4Masquerade))
	}
	NATIPv4Masquerade := [4]byte{}
	copy(NATIPv4Masquerade[:], c.NATIPv4Masquerade)
	result["nat_ipv4_masquerade"] = NATIPv4Masquerade
	if len(c.NATIPv6Masquerade) != 16 {
		return nil, fmt.Errorf("NATIPv6Masquerade must be 16 bytes (got %d)", len(c.NATIPv6Masquerade))
	}
	NATIPv6Masquerade := [16]byte{}
	copy(NATIPv6Masquerade[:], c.NATIPv6Masquerade)
	result["nat_ipv6_masquerade"] = NATIPv6Masquerade
	result["proxy_redirect_via_cilium_net"] = c.ProxyRedirectViaCiliumNet
	TunnelPort := uint16(c.TunnelPort)
	if uint32(TunnelPort) != c.TunnelPort {
		return nil, fmt.Errorf("TunnelPort must fit into a uint16 (value = %d)", c.TunnelPort)
	}
	result["tunnel_port"] = TunnelPort
	TunnelProtocol := uint8(c.TunnelProtocol)
	if uint32(TunnelProtocol) != c.TunnelProtocol {
		return nil, fmt.Errorf("TunnelProtocol must fit into a uint8 (value = %d)", c.TunnelProtocol)
	}
	result["tunnel_protocol"] = TunnelProtocol
	return result, nil
}
