- name: 'datapath-plugins-1'
  kernel: '6.12'
  misc: 'datapathPlugins.enabled=true'
  kube-proxy: 'none'
  kpr: 'true'
  ipv6: 'true'
  tunnel: 'disabled'
  devices: '{eth0,eth1}'
  secondary-network: 'true'
  ingress-controller: 'true'
  lb-acceleration: 'testing-only'
  test-l7: 'false'
